name: CI Build Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore project dependencies
        run: dotnet restore CICDDemo/CICDDemo.csproj

      - name: Build project
        run: dotnet build CICDDemo/CICDDemo.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish CICDDemo/CICDDemo.csproj --configuration Release --output ./publish --no-build
